/**
 * Corpus scanner for the bundled upstream example circuits.
 *
 * The 373 files in `web/public/circuits/` double as a regression corpus. Stage
 * 1 asserts every file loads with zero missing element codes; stage 2 asserts
 * every loadable file runs 100 engine steps with finite outputs. The results
 * are written to a committed golden report and regenerated by `just corpus`.
 *
 * Everything here is pure (no DOM, no React), so the corpus logic is unit
 * testable headlessly.
 */

import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { isElementLine, parseCircuit, type ParsedCircuit } from './netlist';
import { DEFAULT_SETTINGS } from '../model/types';
import type { FrameStats, SimEngine } from '../engine/simulator';

export interface CorpusEntry {
  file: string;
  format: 'plain' | 'xml';
  /** Element kinds and device-model codes this build cannot read. */
  missing: string[];
  /** `38` slider lines, feature tracking only, never a load failure. */
  sliderLines: number;
  load: 'ok' | 'missing' | 'empty' | 'error';
  sim: 'ok' | 'error' | 'notrun';  // 'notrun' whenever load !== 'ok'
  simError?: string;
  /** Why a file landed on `load: 'error'`. */
  loadError?: string;
  converged?: boolean;
}

/** How many engine steps a simulate pass runs. */
export const SIM_STEPS = 100;
/**
 * Wall-clock budget per circuit. The engine's Newton iteration is bounded by
 * `maxSubiterations`, so `run(100)` always returns; this budget only flags a
 * pathological build or machine so slow that the scan would drag. It must sit
 * far above any realistic sim: a circuit that crosses it is recorded as a
 * timeout, and that fixed string lands in the byte-stable golden report, so a
 * slower CI box than the report generator must never trip it.
 */
export const SIM_TIMEOUT_MS = 60_000;

/**
 * Corpus files whose `sim: error` has a diagnosed cause and a named fix.
 *
 * The golden report records that a file fails, never why, and the stage 2
 * no-regression guard skips anything the golden already marks failing. So a
 * diagnosed failure would otherwise sit in the report forever with its reason
 * only in a commit message. Entries here are asserted to be *still failing*:
 * when the named fix lands the corpus test says so, and the line is deleted
 * along with the excuse.
 *
 * This is a record of known causes, not the full failing list. Files that fail
 * for reasons nobody has chased are deliberately absent.
 */
export const DIAGNOSED_SIM_FAILURES: Record<string, string> = {
  'opint-current.txt':
    'No op-amp element here: 20 discrete transistors and one 30 pF capacitor ' +
    'whose file records a voltDiff of 13.68 V. That charge against node ' +
    'voltages the DC pass solved with the capacitor as a 100 M open is the ' +
    'whole failure, and only the very first step fails. Stepping this circuit ' +
    'by hand, one `run(1)` at a time, every step after the first converges and ' +
    'the node voltages stay bounded at the 15 V rails. None of that is visible ' +
    'in the report and it is not worth hunting for: `Circuit::run` breaks out ' +
    'of its loop on the first non-converged step, so steps 2 to 100 never ran, ' +
    'and `simulate` reports `finite: false` whenever a step errored, whatever ' +
    'the voltages were. Needs an adaptive timestep, or the decision not to run ' +
    'DC unless asked. Both belong to a future feature/dc-operating-point.md.',
};

/**
 * Device-model definitions: `32` transistor, `34` diode. Not elements, so they
 * take no slot in the element list, but not harmless passthrough either: the
 * port keeps the model name and simulates the default parameters instead, so a
 * file carrying one is not fully loaded. Counted with the missing kinds until
 * the model tables are parsed.
 */
const MODEL_CODES = new Set(['32', '34']);

/** Files in the corpus directory that are not circuits. */
const NON_CIRCUITS = new Set(['setuplist.txt', 'README.md']);

/** Is every entry in a flat array finite? */
function allFinite(values: ArrayLike<number>): boolean {
  for (let i = 0; i < values.length; i++) {
    if (!Number.isFinite(values[i])) return false;
  }
  return true;
}

/** Splits the parser's unsupported list into missing kinds and features. */
export function plainLoad(parsed: ParsedCircuit): { missing: string[]; sliderLines: number } {
  const missing: string[] = [];
  let sliderLines = 0;
  for (const code of parsed.unsupported) {
    // Sliders are a feature to build, not a component to port, and the pure
    // passthrough types (`h`, `!`, `%`, `?`, `.`, `B`) change nothing at all.
    if (code === '38') sliderLines += 1;
    else if (isElementLine(code) || MODEL_CODES.has(code)) missing.push(code);
  }
  return { missing, sliderLines };
}

/** Entry for a file that could not be read or parsed; the scan must not die. */
function loadErrorEntry(file: string, error: unknown): CorpusEntry {
  return {
    file,
    format: 'plain',
    missing: [],
    sliderLines: 0,
    load: 'error',
    loadError: error instanceof Error ? error.message : String(error),
    sim: 'notrun',
  };
}

/**
 * Scans a directory of circuit files. Only computes the cheap load stage; the
 * caller runs `simulate` for the loadable files and fills in `sim`.
 */
export function scanCorpus(dir: string): CorpusEntry[] {
  const entries: CorpusEntry[] = [];
  for (const file of readdirSync(dir).sort()) {
    if (!file.endsWith('.txt') || NON_CIRCUITS.has(file)) continue;
    let text: string;
    try {
      text = readFileSync(join(dir, file), 'utf8');
    } catch (e) {
      entries.push(loadErrorEntry(file, e));
      continue;
    }
    // The XML root can be preceded by a BOM or blank lines; classify on the
    // first non-blank line rather than the raw first one.
    const head = text.split(/\r?\n/).find((l) => l.trim().length > 0) ?? '';
    if (head.trimStart().startsWith('<cir ')) {
      entries.push({
        file,
        format: 'xml',
        missing: [],
        sliderLines: 0,
        load: 'empty',
        sim: 'notrun',
      });
      continue;
    }
    let parsed: ParsedCircuit;
    try {
      parsed = parseCircuit(text);
    } catch (e) {
      // A throwing element parser must not take down the whole scan.
      entries.push(loadErrorEntry(file, e));
      continue;
    }
    const { missing, sliderLines } = plainLoad(parsed);
    entries.push({
      file,
      format: 'plain',
      missing,
      sliderLines,
      load: missing.length > 0 ? 'missing' : parsed.elements.length > 0 ? 'ok' : 'empty',
      sim: 'notrun',
    });
  }
  return entries;
}

export interface SimResult {
  error?: string;
  converged: boolean;
  finite: boolean;
}

/** Parses, loads and runs a circuit through the real engine. */
export function simulate(engine: SimEngine, text: string): SimResult {
  let parsed: ParsedCircuit;
  try {
    parsed = parseCircuit(text);
  } catch (e) {
    return { error: e instanceof Error ? e.message : String(e), converged: false, finite: false };
  }
  const err = engine.setCircuit(parsed.elements, { ...DEFAULT_SETTINGS, ...parsed.settings }, []);
  if (err) return { error: err, converged: false, finite: false };
  let stats: FrameStats;
  try {
    stats = engine.run(SIM_STEPS);
  } catch (e) {
    return { error: e instanceof Error ? e.message : String(e), converged: false, finite: false };
  }
  if (stats.error) return { error: stats.error, converged: stats.converged, finite: false };
  const finite = allFinite(engine.nodeVoltages()) && allFinite(engine.elementCurrents());
  return { converged: stats.converged, finite };
}

/** Runs the full scan plus simulate stage over a corpus directory. */
export function generateReport(dir: string, engine: SimEngine): CorpusEntry[] {
  const entries = scanCorpus(dir);
  for (const entry of entries) {
    if (entry.format === 'xml' || entry.load !== 'ok') {
      entry.sim = 'notrun';
      continue;
    }
    const text = readFileSync(join(dir, entry.file), 'utf8');
    const start = Date.now();
    const result = simulate(engine, text);
    const elapsed = Date.now() - start;
    if (result.error) {
      entry.sim = 'error';
      entry.simError = result.error;
    } else if (elapsed > SIM_TIMEOUT_MS) {
      // Fixed text only: elapsed time varies between runs and the report is
      // the golden file, so it must be byte-stable.
      entry.sim = 'error';
      entry.simError = 'timeout';
    } else if (result.finite) {
      entry.sim = 'ok';
    } else {
      entry.sim = 'error';
      entry.simError = 'non-finite output';
    }
    entry.converged = result.converged;
  }
  return entries;
}

export interface CorpusSummary {
  total: number;
  xml: number;
  loadOk: number;
  simOk: number;
  sliderLines: number;
}

export function summarize(entries: CorpusEntry[]): CorpusSummary {
  const summary: CorpusSummary = { total: 0, xml: 0, loadOk: 0, simOk: 0, sliderLines: 0 };
  for (const e of entries) {
    summary.total += 1;
    if (e.format === 'xml') summary.xml += 1;
    if (e.load === 'ok') summary.loadOk += 1;
    if (e.sim === 'ok') summary.simOk += 1;
    summary.sliderLines += e.sliderLines;
  }
  return summary;
}

/** Human-readable report, printed by `just corpus`. */
export function formatReport(entries: CorpusEntry[]): string {
  const s = summarize(entries);
  const lines = [`load ok ${s.loadOk}/${s.total}  sim ok ${s.simOk}/${s.total}`];

  const xmlFiles = entries.filter((e) => e.format === 'xml');
  lines.push(`xml format: ${xmlFiles.length} file${xmlFiles.length === 1 ? '' : 's'}`);
  if (xmlFiles.length > 0) lines.push(xmlFiles.map((e) => `  ${e.file}`).join('\n'));

  const sliderFiles = entries.filter((e) => e.sliderLines > 0).length;
  lines.push(`slider lines: ${s.sliderLines} across ${sliderFiles} files`);

  const loadErrors = entries.filter((e) => e.load === 'error');
  if (loadErrors.length > 0) {
    lines.push(`load errors (${loadErrors.length}):`);
    for (const e of loadErrors) lines.push(`  ${e.file}: ${e.loadError ?? 'error'}`);
  }

  const usage = new Map<string, number>();
  for (const e of entries) {
    for (const code of new Set(e.missing)) usage.set(code, (usage.get(code) ?? 0) + 1);
  }
  if (usage.size > 0) {
    lines.push('missing kinds, by corpus usage:');
    const sorted = [...usage.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]));
    for (const [code, count] of sorted) lines.push(`  ${code.padEnd(6)} ${count} file${count === 1 ? '' : 's'}`);
  }

  const notOk = entries.filter((e) => e.sim === 'error');
  if (notOk.length > 0) {
    lines.push(`sim errors (${notOk.length}):`);
    for (const e of notOk) lines.push(`  ${e.file}: ${e.simError ?? 'error'}`);
  }
  return lines.join('\n');
}
