/**
 * Corpus scanner for the bundled upstream example circuits.
 *
 * The 373 files in `web/public/circuits/` double as a regression corpus. Stage
 * 1 asserts every file loads with zero missing element codes; stage 2 asserts
 * every loadable file runs 100 engine steps with finite outputs. The results
 * are written to a committed golden report and regenerated by `just corpus`.
 *
 * Everything here is pure (no DOM, no React), so the corpus logic is unit
 * testable headlessly.
 */

import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { isElementLine, parseCircuit, type ParsedCircuit } from './netlist';
import { registerSessionModel, clearSessionModels } from './subcircuits';
import { DEFAULT_SETTINGS } from '../model/types';
import type { FrameStats, SimEngine } from '../engine/simulator';

export interface CorpusEntry {
  file: string;
  format: 'plain' | 'xml';
  /** True when the file was an upstream XML `<cir>` document, migrated to text
   *  at load by `xmlToText`. Kept so the report can tell the origin. */
  converted?: boolean;
  /** Element kinds and device-model codes this build cannot read. */
  missing: string[];
  /** `38` slider lines, feature tracking only, never a load failure. */
  sliderLines: number;
  load: 'ok' | 'missing' | 'empty' | 'error';
  sim: 'ok' | 'error' | 'notrun';  // 'notrun' whenever load !== 'ok'
  simError?: string;
  /** Why a file landed on `load: 'error'`. */
  loadError?: string;
  converged?: boolean;
}

/** How many engine steps a simulate pass runs. */
export const SIM_STEPS = 100;
/**
 * Wall-clock budget per circuit. The engine's Newton iteration is bounded by
 * `maxSubiterations`, so `run(100)` always returns; this budget only flags a
 * pathological build or machine so slow that the scan would drag. It must sit
 * far above any realistic sim: a circuit that crosses it is recorded as a
 * timeout, and that fixed string lands in the byte-stable golden report, so a
 * slower CI box than the report generator must never trip it.
 */
export const SIM_TIMEOUT_MS = 60_000;

/**
 * Corpus files whose `sim: error` has a diagnosed cause and a named fix.
 *
 * The golden report records that a file fails, never why, and the stage 2
 * no-regression guard skips anything the golden already marks failing. So a
 * diagnosed failure would otherwise sit in the report forever with its reason
 * only in a commit message. Entries here are asserted to be *still failing*:
 * when the named fix lands the corpus test says so, and the line is deleted
 * along with the excuse.
 *
 * This is a record of known causes, not the full failing list. Files that fail
 * for reasons nobody has chased are deliberately absent.
 *
 * `opint-current.txt` lived here until the DC operating point feature: its
 * first step failed because a DC pass solved the 30 pF capacitor as a 100 M
 * open against the node voltages its file records a 13.68 V charge for. The
 * operative fix was honouring flag bit 128: the file's header `$ 1` is
 * bit-128 clear, so under `autoDC` this build runs no DC solve at all and the
 * transient starts from the file's own charge.
 *
 * `qam-256.txt` lived here until the open-current-source pinning feature: a
 *  multiplier VCCS whose output node was left loaded only by an open analog
 *  switch's 1e10 ohm off-resistance solved to ~7.3e6 V, and the two op-amp
 *  followers on it could never settle. The engine now grounds an
 *  effectively-open current-source output that has run away, so the file
 *  converges and the entry is gone.
 *
 * The XML-to-text migration (feature/xml-to-text.md) converted the 38 bundled
 * XML circuits, and every one now loads. The nine that still fail to
 * simulate are port limitations, not conversion bugs: the converted text is
 * what upstream's own text save would have written. Each named cause is the
 * engine feature that would retire the entry.
 */
export const DIAGNOSED_SIM_FAILURES: Record<string, string> = {
  'alu74181.txt':
    'the 5-bit bus splitter feeds the separate S0-S3 and M signals, but the port has no bus support, so all bits join one node and the differently-driven logic inputs short',
  'td4.txt':
    'the decoder composite is built from gates, which the composite engine has no child model for, and the bus splitters and bus logic inputs are dropped, so the microprocessor is structurally broken',
  'td4-add2.txt': 'same decoder composite and bus-splitter limitation as td4.txt',
  'td4-ctr.txt': 'same decoder composite and bus-splitter limitation as td4.txt',
  'td4-ctr-dn.txt': 'same decoder composite and bus-splitter limitation as td4.txt',
  'td4-ctr-up-dn.txt': 'same decoder composite and bus-splitter limitation as td4.txt',
  'cs-opamprail.txt':
    'the clamped gain-1000 VCVS saturates against its +/-10 V rails, where the secant derivative VCVSElm takes across both sample points collapses to the 1e-6 floor and the linearised source becomes a constant, so Newton flip-flops between the rails; upstream breaks the same limit cycle in OpAmpElm with randomised hysteresis, which VCVSElm has no equivalent for, and only the adaptive timestep this file leaves off settles it',
};

/**
 * Device-model definitions: none left. The `32` transistor lines are parsed
 * and resolved on load (transistor-model-lines), like the `34` diode-model
 * lines before them, so they no longer reach the unsupported list at all.
 */
const MODEL_CODES = new Set<string>();

/** Files in the corpus directory that are not circuits. */
const NON_CIRCUITS = new Set(['setuplist.txt', 'README.md']);

/** Is every entry in a flat array finite? */
function allFinite(values: ArrayLike<number>): boolean {
  for (let i = 0; i < values.length; i++) {
    if (!Number.isFinite(values[i])) return false;
  }
  return true;
}

/** Splits the parser's unsupported list into missing kinds and features. */
export function plainLoad(parsed: ParsedCircuit): { missing: string[]; sliderLines: number } {
  const missing: string[] = [];
  for (const code of parsed.unsupported) {
    // The pure passthrough types (`h`, `!`, `%`, `?`, `.`, `B`) change
    // nothing at all.
    if (isElementLine(code) || MODEL_CODES.has(code)) missing.push(code);
  }
  // Sliders (`38`) are parsed into state now, so the feature count is the
  // slider list, never a load failure.
  return { missing, sliderLines: parsed.sliders.length };
}

/** Entry for a file that could not be read or parsed; the scan must not die. */
function loadErrorEntry(file: string, error: unknown): CorpusEntry {
  return {
    file,
    format: 'plain',
    missing: [],
    sliderLines: 0,
    load: 'error',
    loadError: error instanceof Error ? error.message : String(error),
    sim: 'notrun',
  };
}

/**
 * Scans a directory of circuit files. Only computes the cheap load stage; the
 * caller runs `simulate` for the loadable files and fills in `sim`.
 */
export function scanCorpus(dir: string): CorpusEntry[] {
  const entries: CorpusEntry[] = [];
  for (const file of readdirSync(dir).sort()) {
    if (!file.endsWith('.txt') || NON_CIRCUITS.has(file)) continue;
    let text: string;
    try {
      text = readFileSync(join(dir, file), 'utf8');
    } catch (e) {
      entries.push(loadErrorEntry(file, e));
      continue;
    }
    // An upstream XML `<cir>` document is converted to the text format inside
    // parseCircuit (xmlToText), so the scan classifies it like any other file
    // and the conversion error surfaces as a load error.
    const xml = text.split(/\r?\n/).find((l) => l.trim().length > 0) ?? '';
    let parsed: ParsedCircuit;
    try {
      parsed = parseCircuit(text);
    } catch (e) {
      // A throwing element parser must not take down the whole scan.
      entries.push(loadErrorEntry(file, e));
      continue;
    }
    const { missing, sliderLines } = plainLoad(parsed);
    entries.push({
      file,
      format: 'plain',
      ...(xml.trimStart().startsWith('<cir ') ? { converted: true } : {}),
      missing,
      sliderLines,
      load: missing.length > 0 ? 'missing' : parsed.elements.length > 0 ? 'ok' : 'empty',
      sim: 'notrun',
    });
  }
  return entries;
}

export interface SimResult {
  error?: string;
  converged: boolean;
  finite: boolean;
}

/** Parses, loads and runs a circuit through the real engine. */
export function simulate(engine: SimEngine, text: string): SimResult {
  let parsed: ParsedCircuit;
  try {
    parsed = parseCircuit(text);
  } catch (e) {
    return { error: e instanceof Error ? e.message : String(e), converged: false, finite: false };
  }
  // The file's own `.` subcircuit lines join the session library, so a 410
  // element's geometry (posts, body) resolves the same way the store's load
  // resolves it. The corpus scan is per-file, so a stale library from the
  // previous file cannot leak across: register fresh each time.
  clearSessionModels();
  for (const model of parsed.compositeModels) registerSessionModel(model);
  const err = engine.setCircuit(parsed.elements, { ...DEFAULT_SETTINGS, ...parsed.settings }, []);
  if (err) return { error: err, converged: false, finite: false };
  let stats: FrameStats;
  try {
    stats = engine.run(SIM_STEPS);
  } catch (e) {
    return { error: e instanceof Error ? e.message : String(e), converged: false, finite: false };
  }
  if (stats.error) return { error: stats.error, converged: stats.converged, finite: false };
  const finite = allFinite(engine.nodeVoltages()) && allFinite(engine.elementCurrents());
  return { converged: stats.converged, finite };
}

/** Runs the full scan plus simulate stage over a corpus directory. */
export function generateReport(dir: string, engine: SimEngine): CorpusEntry[] {
  const entries = scanCorpus(dir);
  for (const entry of entries) {
    if (entry.load !== 'ok') {
      entry.sim = 'notrun';
      continue;
    }
    const text = readFileSync(join(dir, entry.file), 'utf8');
    const start = Date.now();
    const result = simulate(engine, text);
    const elapsed = Date.now() - start;
    if (result.error) {
      entry.sim = 'error';
      entry.simError = result.error;
    } else if (elapsed > SIM_TIMEOUT_MS) {
      // Fixed text only: elapsed time varies between runs and the report is
      // the golden file, so it must be byte-stable.
      entry.sim = 'error';
      entry.simError = 'timeout';
    } else if (result.finite) {
      entry.sim = 'ok';
    } else {
      entry.sim = 'error';
      entry.simError = 'non-finite output';
    }
    entry.converged = result.converged;
  }
  return entries;
}

export interface CorpusSummary {
  total: number;
  xml: number;
  loadOk: number;
  simOk: number;
  sliderLines: number;
}

export function summarize(entries: CorpusEntry[]): CorpusSummary {
  const summary: CorpusSummary = { total: 0, xml: 0, loadOk: 0, simOk: 0, sliderLines: 0 };
  for (const e of entries) {
    summary.total += 1;
    if (e.format === 'xml') summary.xml += 1;
    if (e.load === 'ok') summary.loadOk += 1;
    if (e.sim === 'ok') summary.simOk += 1;
    summary.sliderLines += e.sliderLines;
  }
  return summary;
}

/** Human-readable report, printed by `just corpus`. */
export function formatReport(entries: CorpusEntry[]): string {
  const s = summarize(entries);
  const lines = [`load ok ${s.loadOk}/${s.total}  sim ok ${s.simOk}/${s.total}`];

  const converted = entries.filter((e) => e.converted);
  lines.push(`converted from xml: ${converted.length} file${converted.length === 1 ? '' : 's'}`);
  if (converted.length > 0) lines.push(converted.map((e) => `  ${e.file}`).join('\n'));

  const sliderFiles = entries.filter((e) => e.sliderLines > 0).length;
  lines.push(`slider lines: ${s.sliderLines} across ${sliderFiles} files`);

  const loadErrors = entries.filter((e) => e.load === 'error');
  if (loadErrors.length > 0) {
    lines.push(`load errors (${loadErrors.length}):`);
    for (const e of loadErrors) lines.push(`  ${e.file}: ${e.loadError ?? 'error'}`);
  }

  const usage = new Map<string, number>();
  for (const e of entries) {
    for (const code of new Set(e.missing)) usage.set(code, (usage.get(code) ?? 0) + 1);
  }
  if (usage.size > 0) {
    lines.push('missing kinds, by corpus usage:');
    const sorted = [...usage.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]));
    for (const [code, count] of sorted) lines.push(`  ${code.padEnd(6)} ${count} file${count === 1 ? '' : 's'}`);
  }

  const notOk = entries.filter((e) => e.sim === 'error');
  if (notOk.length > 0) {
    lines.push(`sim errors (${notOk.length}):`);
    for (const e of notOk) lines.push(`  ${e.file}: ${e.simError ?? 'error'}`);
  }
  return lines.join('\n');
}
